-- SQL Code to safely create tables, dropping them first if they already exist

-- Drop tables in reverse order of dependency
DROP TABLE IF EXISTS Line;
DROP TABLE IF EXISTS Invoice;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Vendor;

-- Create tables

-- Vendor table
CREATE TABLE Vendor (
    V_CODE VARCHAR(10) PRIMARY KEY,
    V_NAME VARCHAR(50),
    V_CONTACT VARCHAR(50),
    V_AREACODE CHAR(5),
    V_PHONE VARCHAR(15),
    V_STATE CHAR(2),
    V_ORDER DECIMAL(10,2)
);

-- Customer table
CREATE TABLE Customer (
    CUS_CODE VARCHAR(10) PRIMARY KEY,
    CUS_LNAME VARCHAR(50),
    CUS_FNAME VARCHAR(50),
    CUS_INITIAL CHAR(1),
    CUS_AREACODE CHAR(5),
    CUS_PHONE VARCHAR(15),
    CUS_BALANCE DECIMAL(10,2)
);

-- Product table
CREATE TABLE Product (
    P_CODE VARCHAR(10) PRIMARY KEY,
    P_DESCRIPT VARCHAR(100),
    P_INDATE DATE,
    P_QOH INT,
    P_MIN INT,
    P_PRICE DECIMAL(10,2),
    P_DISCOUNT DECIMAL(5,2),
    V_CODE VARCHAR(10),
    FOREIGN KEY (V_CODE) REFERENCES Vendor(V_CODE)
);

-- Invoice table
CREATE TABLE Invoice (
    INV_NUMBER VARCHAR(10) PRIMARY KEY,
    CUS_CODE VARCHAR(10),
    INV_DATE DATE,
    FOREIGN KEY (CUS_CODE) REFERENCES Customer(CUS_CODE)
);

-- Line table
CREATE TABLE Line (
    INV_NUMBER VARCHAR(10),
    LINE_NUMBER INT,
    P_CODE VARCHAR(10),
    LINE_UNITS INT,
    LINE_PRICE DECIMAL(10,2),
    PRIMARY KEY (INV_NUMBER, LINE_NUMBER),
    FOREIGN KEY (INV_NUMBER) REFERENCES Invoice(INV_NUMBER),
    FOREIGN KEY (P_CODE) REFERENCES Product(P_CODE)
);
