-- SQL Code to safely create tables, dropping them first if they already exist

-- Drop tables in reverse order of dependency
DROP TABLE IF EXISTS Line;
DROP TABLE IF EXISTS Invoice;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Vendor;

-- Create Vendor table
CREATE TABLE Vendor (
    V_CODE VARCHAR(10) NOT NULL PRIMARY KEY,
    V_NAME VARCHAR(50) NOT NULL,
    V_CONTACT VARCHAR(50) NOT NULL,
    V_AREACODE CHAR(5) NOT NULL,
    V_PHONE VARCHAR(15) NOT NULL,
    V_STATE CHAR(2) NOT NULL,
    V_ORDER DECIMAL(10,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Create Customer table
CREATE TABLE Customer (
    CUS_CODE VARCHAR(10) NOT NULL PRIMARY KEY,
    CUS_LNAME VARCHAR(50) NOT NULL,
    CUS_FNAME VARCHAR(50) NOT NULL,
    CUS_INITIAL CHAR(1) NOT NULL,
    CUS_AREACODE CHAR(5) NOT NULL,
    CUS_PHONE VARCHAR(15) NOT NULL,
    CUS_BALANCE DECIMAL(10,2) NOT NULL DEFAULT 0.00
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Create Product table
CREATE TABLE Product (
    P_CODE VARCHAR(10) NOT NULL PRIMARY KEY,
    P_DESCRIPT VARCHAR(100) NOT NULL,
    P_INDATE DATE NOT NULL,
    P_QOH INT NOT NULL,
    P_MIN INT NOT NULL,
    P_PRICE DECIMAL(10,2) NOT NULL,
    P_DISCOUNT DECIMAL(5,2) NOT NULL,
    V_CODE VARCHAR(10) NOT NULL,
    FOREIGN KEY (V_CODE) REFERENCES Vendor(V_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Create Invoice table
CREATE TABLE Invoice (
    INV_NUMBER VARCHAR(10) NOT NULL PRIMARY KEY,
    CUS_CODE VARCHAR(10) NOT NULL,
    INV_DATE DATE NOT NULL,
    FOREIGN KEY (CUS_CODE) REFERENCES Customer(CUS_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Create Line table
CREATE TABLE Line (
    INV_NUMBER VARCHAR(10) NOT NULL,
    LINE_NUMBER INT NOT NULL,
    P_CODE VARCHAR(10) NOT NULL,
    LINE_UNITS INT NOT NULL,
    LINE_PRICE DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (INV_NUMBER, LINE_NUMBER),
    FOREIGN KEY (INV_NUMBER) REFERENCES Invoice(INV_NUMBER),
    FOREIGN KEY (P_CODE) REFERENCES Product(P_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
